### ISSUE TITLE
🏗️🔔 setting the `engines` field in `package.json`

### ISSUE THREAD

**Issue by TKDev7** [OpenINF/openinf.github.io#1017]
I have noticed this project has the engine-strict flag set but without the engines field in package.json. If my understanding is correct, that flag will have no affect no?

**Comment by DerekNonGeneric** [comment]
Hello @MrHBS, thanks for opening this issue.

> I have noticed this project has the engine-strict flag set [&hellip;]

If you are referring to the `.npmrc` file:
https://github.com/OpenINF/openinf.github.io/blob/5752ca31d2faf0b4049257b00067e44b359132e1/.npmrc#L1

&hellip; you are correct.

> [&hellip;] but without the engines field in package.json.

Also correct, the `engines` field is non-existent in our `package.json` file:
https://github.com/OpenINF/openinf.github.io/blob/5752ca31d2faf0b4049257b00067e44b359132e1/package.json#L1-L8

> If my understanding is correct, that flag will have no affect no?

There was a time when we were using the stock **npm** that ships w/ Node.js, and the docs for `engine-strict` currently state the following.

> If set to true, then npm will stubbornly refuse to install (or even consider installing) any package that claims to not be compatible with the current Node.js version.
>
> This can be overridden by setting the `--force` flag.
> &mdash;https://docs.npmjs.com/cli/v10/using-npm/config#engine-strict

However, we switched to **pnpm** along the way, which also does have functionality for this option:

> If this is enabled, pnpm will not install any package that claims to not be compatible with the current Node version.
>
> Regardless of this configuration, installation will always fail if a project (not a dependency) specifies an incompatible version in its `engines` field.
> &mdash;https://pnpm.io/npmrc#engine-strict

This seems to be the bit you are inquiring about, which **pnpm** seems to have slightly changed its meaning over time.

**Comment by DerekNonGeneric** [comment]
**So, to answer the question,** setting `engine-strict` does have some stated effect _even without specifying the engines field_ (as we currently have it). Since this is enabled, as the docs state, &ldquo;**pnpm** will not install any package that claims to not be compatible with the current Node version&rdquo;.

However, whether we would want the installation to always fail by specifying a potentially incompatible version in our `engines` field appears to be another decision we could be making here.

According to the current **pnpm** docs for the `engines` field, which states the following.

> You can specify the version of Node and pnpm that your software works on:
>
> [&hellip;]
>
> During local development, pnpm will always fail with an error message if its version does not match the one specified in the `engines` field.
>
> Unless the user has set the `engine-strict` config flag (see [.npmrc](https://pnpm.io/npmrc#engine-strict)), this field is advisory only and will only produce warnings when your package is installed as a dependency.
> &mdash;https://pnpm.io/package_json#engines

That bit of the docs does still seem incomplete tho seeing as how previously stated above (by the [**pnpm** engine-strict](https://pnpm.io/npmrc#engine-strict) docs), the installation will always fail if a project (not a dependency) specifies an incompatible version in its `engines` field, so this will not end up being &ldquo;advisory only&rdquo; only producing warnings, but would actually be leading to project dependency installation failure.

Additionally, by specifying the version of **pnpm** in the `engines` field, **pnpm** itself will always fail with an error message if its version does not match the one specified in the `engines` field.

How strict we want to be here is somewhat up for debate, so i added the https://github.com/OpenINF/openinf.github.io/labels/discuss label, but i generally prefer to be rather strict about this&hellip;

**Comment by TKDev7** [comment]
> pnpm will not install any package that claims to not be compatible with the current Node version.

This is what is confusing me. How will pnpm know the current Node version without the engines field? I thought that was the whole point of that field; for npm/pnpm to read that field and find what Node versions is compatible with your project. Unless you are saying they get this information from the node executable installed in your system?

**Comment by DerekNonGeneric** [comment]
Currently still determining their exact implementation, but @MrHBS, if you could, please have a look at https://github.com/tc39/tc39.github.io/pull/356 as i think we'd appreciate your advice on what you'd prefer us to do here.

Once you're reasonably sure, please do the honors yourself; one of us (likely me) will review your PR immediately.😀

**Comment by TKDev7** [comment]
I have no idea what the best approach here would be. The way I found this repo was by searching for engine-strict on GitHub to see how other developers use this flag. So I came across this repo and seeing how well thought out this project is I thought of asking the devs here for clarification regarding omitting the engines field when using the engine-strict flag. And well it appears we are all confused lol.

**Comment by DerekNonGeneric** [comment]
> So I came across this repo and seeing how well thought out this project is I thought of asking the devs here [&hellip;]

Thank you for your inquiry and compliment! 😊🙏

> And well it appears we are all confused lol.

Well, it has been a while since us doing this (and the pnpm docs even changed in most recent versions), but the correct answer is that we would like our builds to be deterministic (perhaps failing otherwise); hence, setting the `engines` field (for both `node` &amp; `pnpm`) in `package.json` is generally preferable&hellip; 👍

We at @OpenINF may have some unique (rare) `engine` needs, tho!

See: https://twitter.com/DerekNonGeneric/status/1701961602667291100

**Comment by DerekNonGeneric** [comment]
@MrHBS et al., would you mind looking at a rough draft of my proposed solution to this issue in #1023?
